interface TopArtistRecap {
  name: string
  plays: number
  imageDataUrl?: string | null
}

interface TopAlbumRecap {
  name: string
  plays: number
  imageDataUrl?: string | null
}

export interface YearRecapInfographicData {
  year: number
  totalPlays: number
  activeDays: number
  uniqueArtists: number
  uniqueAlbums: number
  uniqueTracks: number
  topArtists: TopArtistRecap[]
  topAlbum?: TopAlbumRecap
}

function escapeXml(value: string): string {
  return value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

function truncate(value: string, maxChars: number): string {
  if (value.length <= maxChars) return value
  return `${value.slice(0, Math.max(0, maxChars - 1))}…`
}

function artistCardSvg(x: number, y: number, index: number, artist: TopArtistRecap): string {
  const img = artist.imageDataUrl
    ? `<image href="${escapeXml(artist.imageDataUrl)}" x="${x + 12}" y="${y + 12}" width="72" height="72" preserveAspectRatio="xMidYMid slice" />`
    : `<rect x="${x + 12}" y="${y + 12}" width="72" height="72" rx="10" fill="#fca5a5" />`

  return `
    <rect x="${x}" y="${y}" width="360" height="96" rx="16" fill="#ffffff" />
    ${img}
    <text x="${x + 100}" y="${y + 42}" font-size="20" font-weight="700" fill="#111827">${index + 1}. ${escapeXml(truncate(artist.name, 26))}</text>
    <text x="${x + 100}" y="${y + 70}" font-size="16" fill="#6b7280">${artist.plays.toLocaleString()} plays</text>
  `
}

function buildSvg(data: YearRecapInfographicData): string {
  const topArtists = data.topArtists.slice(0, 3)
  const stats = [
    { label: 'Total Plays', value: data.totalPlays.toLocaleString() },
    { label: 'Active Days', value: data.activeDays.toLocaleString() },
    { label: 'Artists', value: data.uniqueArtists.toLocaleString() },
    { label: 'Albums', value: data.uniqueAlbums.toLocaleString() },
    { label: 'Tracks', value: data.uniqueTracks.toLocaleString() },
  ]

  const statRects = stats.map((s, i) => {
    const x = 80 + i * 208
    return `
      <rect x="${x}" y="170" width="192" height="112" rx="16" fill="#ffffff" />
      <text x="${x + 16}" y="208" font-size="15" fill="#6b7280">${escapeXml(s.label)}</text>
      <text x="${x + 16}" y="248" font-size="32" font-weight="700" fill="#111827">${escapeXml(s.value)}</text>
    `
  }).join('')

  const artistBlocks = topArtists.map((a, i) => artistCardSvg(80, 330 + i * 112, i, a)).join('')

  const topAlbumSection = data.topAlbum
    ? `
      <rect x="80" y="690" width="1040" height="260" rx="20" fill="#ffffff" />
      <text x="108" y="734" font-size="22" font-weight="700" fill="#111827">Top Album</text>
      ${data.topAlbum.imageDataUrl
        ? `<image href="${escapeXml(data.topAlbum.imageDataUrl)}" x="108" y="756" width="170" height="170" preserveAspectRatio="xMidYMid slice" />`
        : `<rect x="108" y="756" width="170" height="170" rx="14" fill="#fecaca" />`
      }
      <text x="304" y="808" font-size="28" font-weight="700" fill="#111827">${escapeXml(truncate(data.topAlbum.name, 45))}</text>
      <text x="304" y="848" font-size="20" fill="#6b7280">${data.topAlbum.plays.toLocaleString()} plays</text>
    `
    : ''

  return `
<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="1000" viewBox="0 0 1200 1000">
  <defs>
    <linearGradient id="bg" x1="0" y1="0" x2="1" y2="1">
      <stop offset="0%" stop-color="#fee2e2" />
      <stop offset="100%" stop-color="#ffffff" />
    </linearGradient>
  </defs>
  <rect x="0" y="0" width="1200" height="1000" fill="url(#bg)" />
  <text x="80" y="90" font-size="56" font-weight="800" fill="#991b1b">My ${data.year} Recap</text>
  <text x="80" y="126" font-size="20" fill="#7f1d1d">Generated by Last.fm Visualizer</text>
  ${statRects}
  <text x="80" y="312" font-size="24" font-weight="700" fill="#111827">Top Artists</text>
  ${artistBlocks}
  ${topAlbumSection}
</svg>`
}

export async function imageUrlToDataUrl(url: string): Promise<string | null> {
  try {
    const response = await fetch(url)
    if (!response.ok) {
      console.warn(`Infographic image fetch failed (${response.status}): ${url}`)
      return null
    }
    const blob = await response.blob()
    return await new Promise<string>((resolve, reject) => {
      const reader = new FileReader()
      reader.onloadend = () => resolve(String(reader.result))
      reader.onerror = () => reject(new Error(`Could not read image blob for ${url}`))
      reader.readAsDataURL(blob)
    })
  } catch (error) {
    console.warn(`Infographic image fetch failed: ${url}`, error)
    return null
  }
}

export async function downloadYearRecapInfographicPng(data: YearRecapInfographicData): Promise<void> {
  const svgText = buildSvg(data)
  const svgBlob = new Blob([svgText], { type: 'image/svg+xml;charset=utf-8' })
  const svgUrl = URL.createObjectURL(svgBlob)
  const image = new Image()

  await new Promise<void>((resolve, reject) => {
    image.onload = () => resolve()
    image.onerror = () => reject(new Error('Could not render infographic SVG.'))
    image.src = svgUrl
  })

  const scale = 2
  const canvas = document.createElement('canvas')
  canvas.width = 1200 * scale
  canvas.height = 1000 * scale
  const ctx = canvas.getContext('2d')
  if (!ctx) {
    URL.revokeObjectURL(svgUrl)
    throw new Error('Could not initialize canvas for infographic export.')
  }
  ctx.scale(scale, scale)
  ctx.drawImage(image, 0, 0, 1200, 1000)

  const pngBlob = await new Promise<Blob>((resolve, reject) => {
    canvas.toBlob(blob => {
      if (!blob) {
        reject(new Error('Could not encode infographic PNG.'))
        return
      }
      resolve(blob)
    }, 'image/png')
  })

  URL.revokeObjectURL(svgUrl)

  const pngUrl = URL.createObjectURL(pngBlob)
  const a = document.createElement('a')
  a.href = pngUrl
  a.download = `lastfm-recap-${data.year}.png`
  a.click()
  URL.revokeObjectURL(pngUrl)
}
